Set($AceEditorScripsEnable,1);
Set($AceEditorTemplatesEnable,0);
Set($AceEditorWidth,'700px');
Set($AceEditorMinLines,'5');
Set($AceEditorMaxLines,'100');
Set($AceEditorTheme,'monokai');
Set($AceEditorScripsMode,'perl');
Set($AceEditorTemplatesMode,'html');
1;
